### PR TITLE
pull request for some edits

### PR DESCRIPTION
**Pull request by foo-2**
This is an extended description of the change.  I added the following text: Some change to the readme text...  Preceding text from the commit message, but adding to the description here as the pull request is opened.

### CODE REVIEW

**Comment by foo-2** [comment]
Requesting review from two other users (@foo-3 and @ZekeWagner).  This is an _edit_ to a comment.

**Comment by foo-3** [comment]
This is another comment.
A link in the comment: [link to google](http://www.google.com)

**Review by foo-3 — COMMENTED** [review]
This is a review of this pull request for some edits, comment type.  Here is my comment: Is this really all that was changed?

**Comment by foo-2** [comment]
Yes, this is really all that was changed.

**Comment by foo-3** [comment]
OK.  These changes look good.

**Comment by foo-3** [comment]
Closing this pull request.  Not exactly sure if this pull will still wait for other reviewers?

**Comment by foo-3** [comment]
Hmmm... Probably need to reopen as we wait for all reviewers.

Review complete.

**Pull request merged**
